export const FETCH_WORD_LIST = "FETCH_WORD_LIST";
export const FETCH_WORD_LIST_SUCCESS = "FETCH_WORD_LIST_SUCCESS";
export const INCREMENT_WORD_COUNT = "INCREMENT_WORD_COUNT";
export const ADD_ANSWER_LIST = "ADD_ANSWER_LIST";
export const FETCH_ANSWER_LIST = "FETCH_ANSWER_LIST";
export const RESET_ANSWER_LIST = "RESET_ANSWER_LIST";
export const RESET_WORD_COUNT = "RESET_WORD_COUNT";