export const FETCH_MAJOR_SEGMENT = 'FETCH_MAJOR_SEGMENT';
export const FETCH_MAJOR_SEGMENT_SUCCESS = 'FETCH_MAJOR_SEGMENT_SUCCESS';
export const FETCH_USER_MAJOR_SEGMENT_STATUSES = 'FETCH_USER_MAJOR_SEGMENT_STATUSES';
export const FETCH_USER_MAJOR_SEGMENT_STATUSES_SUCCESS = 'FETCH_USER_MAJOR_SEGMENT_STATUSES_SUCCESS';