export const FETCH_SEGMENTS = 'FETCH_SEGMENTS';
export const FETCH_SEGMENTS_SUCCESS = 'FETCH_SEGMENTS_SUCCESS';
export const FETCH_USER_SEGMENT_STATUSES = 'FETCH_USER_SEGMENT_STATUSES';
export const FETCH_USER_SEGMENT_STATUSES_SUCCESS = 'FETCH_USER_SEGMENT_STATUSES_SUCCESS';
export const FETCH_GENERATE_ARTICLE = 'FETCH_GENERATE_ARTICLE';