# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy PHP app to Azure Web App - VocabularyBuilding

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
        env:
          update: true

      - name: Check PHP version
        run: php -v

      - name: Update Composer
        run: composer self-update --2

      - name: Check PHP version
        run: php -v

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Node.js dependencies
        run: |
          rm -rf node_modules
          npm ci

      - name: Build React app
        run: |
          npm run build

      - name: Create deployment package
        run: |
          rm -rf node_modules
          zip -r release.zip . -x "*.git*" "node_modules/*" "tests/*" "storage/framework/cache/*" "storage/framework/sessions/*" "storage/framework/views/*"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: php-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      contents: read
      id-token: write

    steps:
          
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: php-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Check deployment package size
        run: |
          du -sh .
          find . -type f | wc -l

      - name: Setup PHP for deployment
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Check PHP version on deployment
        run: php -v

      - name: Create .env file
        run: |
          echo "LOG_CHANNEL=stack" >> .env
          echo "LOG_LEVEL=debug" >> .env
          # 他の必要な環境変数も追加

      - name: Set storage permissions
        run: |
          chmod -R 775 storage
          chmod -R 775 bootstrap/cache

      - name: Set up environment variables
        run: |
          echo "APP_ENV=production" >> .env
          echo "APP_KEY=${{ secrets.APP_KEY }}" >> .env
          echo "APP_DEBUG=false" >> .env
          echo "DB_CONNECTION=${{ secrets.DB_CONNECTION }}" >> $GITHUB_ENV
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
          cat .env
        
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_EFD747454B3F4FA1A7F4B56730782DDB }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C3C0316F42DA4B9190486306EE9A56EC }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_74A320CC9E7942818F953D1BCEC74478 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'VocabularyBuilding'
          slot-name: 'Production'
          package: .

      - name: Debug environment variables
        run: |
          echo "DB_HOST: ${{ env.DB_HOST }}"
          echo "DB_PORT: ${{ env.DB_PORT }}"
          echo "DB_DATABASE: ${{ env.DB_DATABASE }}"
          echo "DB_USERNAME: ${{ env.DB_USERNAME }}"

      - name: List all environment variables
        run: env | sort

      - name: Check Secrets availability
        run: |
          echo "DB_CONNECTION is set: ${{ secrets.DB_CONNECTION != '' }}"
          echo "DB_HOST is set: ${{ secrets.DB_HOST != '' }}"
          echo "DB_PORT is set: ${{ secrets.DB_PORT != '' }}"
          echo "DB_DATABASE is set: ${{ secrets.DB_DATABASE != '' }}"
          echo "DB_USERNAME is set: ${{ secrets.DB_USERNAME != '' }}"
          echo "DB_PASSWORD is set: ${{ secrets.DB_PASSWORD != '' }}"
          
      - name: Debug database connection
        env:
          DB_CONNECTION: ${{ secrets.DB_CONNECTION }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          php -r "var_dump(getenv());"
          php artisan config:clear
          php artisan config:cache
          php artisan tinker --execute="DB::connection()->getPdo();"

      - name: Debug database connection
        run: |
          php -r "
          \$host = getenv('DB_HOST');
          \$port = getenv('DB_PORT');
          \$database = getenv('DB_DATABASE');
          \$username = getenv('DB_USERNAME');
          \$password = getenv('DB_PASSWORD');
          echo \"Attempting to connect to database...\n\";
          echo \"Host: \$host\n\";
          echo \"Port: \$port\n\";
          echo \"Database: \$database\n\";
          echo \"Username: \$username\n\";
          \$dsn = \"mysql:host=\$host;port=\$port;dbname=\$database\";
          try {
              \$pdo = new PDO(\$dsn, \$username, \$password, [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]);
              echo \"Connection successful!\n\";
          } catch (PDOException \$e) {
              echo \"Connection failed: \" . \$e->getMessage() . \"\n\";
          }
          "

      - name: Test database connection
        env:
          DB_CONNECTION: ${{ secrets.DB_CONNECTION }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MYSQL_ATTR_SSL_CA: /etc/ssl/certs/ca-certificates.crt
        run: |
          php -r "
            \$host = getenv('DB_HOST');
            \$port = getenv('DB_PORT');
            \$db   = getenv('DB_DATABASE');
            \$user = getenv('DB_USERNAME');
            \$pass = getenv('DB_PASSWORD');
            \$ssl_ca = getenv('MYSQL_ATTR_SSL_CA');
            
            try {
              \$dsn = \"mysql:host=\$host;port=\$port;dbname=\$db\";
              \$options = [
                PDO::MYSQL_ATTR_SSL_CA => \$ssl_ca,
                PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT => false,
              ];
              \$pdo = new PDO(\$dsn, \$user, \$pass, \$options);
              echo 'Connected successfully';
            } catch (PDOException \$e) {
              echo 'Connection failed: ' . \$e->getMessage();
            }
          "

      - name: Test database connection2
        env:
          DB_CONNECTION: mysql
          DB_HOST: vocabularybuilding-server.mysql.database.azure.com
          DB_PORT: 3306
          DB_DATABASE: vocabularybuilding-database
          DB_USERNAME: uvlutslbxt
          DB_PASSWORD: MRGkcZL5
          MYSQL_ATTR_SSL_CA: /etc/ssl/certs/ca-certificates.crt
        run: |
          php -r "
            \$host = getenv('DB_HOST');
            \$port = getenv('DB_PORT');
            \$db   = getenv('DB_DATABASE');
            \$user = getenv('DB_USERNAME');
            \$pass = getenv('DB_PASSWORD');
            \$ssl_ca = getenv('MYSQL_ATTR_SSL_CA');
            
            try {
              \$dsn = \"mysql:host=\$host;port=\$port;dbname=\$db\";
              \$options = [
                PDO::MYSQL_ATTR_SSL_CA => \$ssl_ca,
                PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT => false,
              ];
              \$pdo = new PDO(\$dsn, \$user, \$pass, \$options);
              echo 'Connected successfully';
            } catch (PDOException \$e) {
              echo 'Connection failed: ' . \$e->getMessage();
            }
          "

      - name: Run migrations and seed database
        env:
          DB_CONNECTION: mysql
          DB_HOST: vocabularybuilding-server.mysql.database.azure.com
          DB_PORT: 3306
          DB_DATABASE: vocabularybuilding-database
          DB_USERNAME: uvlutslbxt
          DB_PASSWORD: MRGkcZL5
          MYSQL_ATTR_SSL_CA: /etc/ssl/certs/ca-certificates.crt

        run: |
          php artisan config:clear
          php artisan migrate --force
          php artisan db:seed --force

      - name: Verify .env file on Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'YourAppName'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          startup-command: 'cat /home/site/wwwroot/.env'